// Generated by CoffeeScript 1.6.2
var Path, processtools, _;

_ = require('underscore');

processtools = require('./processtools');

Path = {
  toObject: function() {
    var _ref;

    return {
      nodes: this._nodes || null,
      relationships: this._relationships,
      data: (_ref = this._data) != null ? _ref.data : void 0,
      id: this.id,
      getParent: function() {
        return this;
      }
    };
  }
};

exports.extend = function(pathObject) {
  if (typeof pathObject !== 'object') {
    return pathObject;
  }
  return _.extend(pathObject, Path);
};
