// Generated by CoffeeScript 1.6.2
var processtools;

processtools = require('./processtools');

module.exports = function(graphdb, mongoose, options) {
  var Node, node, _loadDocumentFromNode, _loadDocumentFromNodeUrl;

  node = graphdb.createNode();
  Node = node.constructor;
  _loadDocumentFromNode = function(node, cb) {
    var collection, collectionName, _id, _ref, _ref1;

    if (!(node != null ? (_ref = node._data) != null ? _ref.data : void 0 : void 0)) {
      return cb("No node object given", cb);
    }
    _id = new processtools.getObjectIdFromString(node.getMongoId());
    collectionName = node.getCollectionName();
    if (!(mongoose && typeof cb === 'function')) {
      cb("No mongodb connection -> init({..., >>mongodb: mongodbconnection<<, ...", null);
    }
    collection = ((_ref1 = mongoose.connections[0]) != null ? _ref1.collection(collectionName) : void 0) || mongoose.collection(collectionName);
    return collection.findOne({
      _id: _id
    }, cb);
  };
  _loadDocumentFromNodeUrl = function(url, cb) {
    return graphdb.getNode(url, function(err, node) {
      if (err) {
        return cb(err, node);
      }
      return _loadDocumentFromNode(node, cb);
    });
  };
  Node.prototype.getCollectionName = function() {
    var _ref, _ref1, _ref2, _ref3;

    return ((_ref = this._data) != null ? (_ref1 = _ref.indexed) != null ? (_ref2 = _ref1.match(/\/data\/index\/node\/(.+?)\//)) != null ? _ref2[1] : void 0 : void 0 : void 0) || ((_ref3 = this._data) != null ? _ref3.data.collection : void 0);
  };
  Node.prototype.getMongoId = function() {
    var _ref, _ref1;

    return (_ref = this._data) != null ? (_ref1 = _ref.data) != null ? _ref1._id : void 0 : void 0;
  };
  return Node.prototype.getDocument = function(cb) {
    var _ref, _ref1, _ref2;

    if (this.document && typeof cb === 'function') {
      return cb(null, this.document);
    }
    if ((_ref = this._data) != null ? (_ref1 = _ref.data) != null ? _ref1._id : void 0 : void 0) {
      return _loadDocumentFromNode(this, cb);
    } else {
      return _loadDocumentFromNodeUrl((_ref2 = this._data) != null ? _ref2.self : void 0, cb);
    }
  };
};
