// Generated by CoffeeScript 1.6.2
var processtools;

processtools = require('./processtools');

module.exports = function(graphdb, mongodb, options) {
  var Node, node;

  node = graphdb.createNode();
  Node = node.constructor;
  Node.prototype.getCollectionName = function() {
    var _ref, _ref1, _ref2;

    return (_ref = this._data) != null ? (_ref1 = _ref.indexed) != null ? (_ref2 = _ref1.match(/\/data\/index\/node\/(.+?)\//)) != null ? _ref2[1] : void 0 : void 0 : void 0;
  };
  Node.prototype.getMongoId = function() {
    var _ref, _ref1;

    return (_ref = this._data) != null ? (_ref1 = _ref.data) != null ? _ref1._id : void 0 : void 0;
  };
  return Node.prototype.getDocument = function(cb) {
    var collectionName, _id;

    if (this.document && typeof cb === 'function') {
      return cb(null, this.document);
    }
    _id = new processtools.getObjectIdFromString(this.getMongoId());
    collectionName = this.getCollectionName();
    if (!(mongodb && typeof cb === 'function')) {
      cb("No mongodb connection -> init({..., >>mongodb: mongodbconnection<<, ...", null);
    }
    return mongodb.collection(collectionName).findOne({
      _id: _id
    }, cb);
  };
};
