// Generated by CoffeeScript 1.6.2
var processtools, _s;

_s = require('underscore.string');

processtools = require('./processtools');

module.exports = function(globalOptions) {
  var Document, functionName, graphdb, mongoose, node, _i, _len, _queryGraphDB, _ref;

  mongoose = globalOptions.mongoose;
  graphdb = globalOptions.neo4j;
  if (globalOptions.overrideProtypeFunctions !== true) {
    _ref = ['removeNode', 'shortestPathTo', 'removeRelationships', 'removeRelationshipsBetween', 'removeRelationshipsFrom', 'removeRelationshipsTo', 'outgoingRelationships', 'incomingRelationships', 'allRelationships', 'queryRelationships', 'queryGraph', 'createRelationshipBetween', 'createRelationshipFrom', 'createRelationshipTo', 'getNodeId', 'findOrCreateCorrespondingNode', 'findCorrespondingNode'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      functionName = _ref[_i];
      if (typeof mongoose.Document.prototype[functionName] !== 'undefined') {
        throw new Error("Will not override mongoose::Document.prototype." + functionName);
      }
    }
  }
  Document = mongoose.Document;
  processtools.setMongoose(mongoose);
  node = graphdb.createNode();
  _queryGraphDB = function(cypher, options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    return graphdb.query(cypher, null, function(errGraph, map) {
      var data, result, _ref2, _ref3;

      if ((_ref2 = options.debug) == null) {
        options.debug = false;
      }
      if (options.debug) {
        options.debug = {};
      }
      if (options.debug) {
        options.debug.cypher = cypher;
      }
      if ((_ref3 = options.loadDocuments) == null) {
        options.loadDocuments = true;
      }
      if (options.loadDocuments && (map != null ? map.length : void 0) > 0) {
        data = (function() {
          var _j, _len1, _results;

          _results = [];
          for (_j = 0, _len1 = map.length; _j < _len1; _j++) {
            result = map[_j];
            if (options.processPart) {
              _results.push(result[options.processPart]);
            } else {
              _results.push(result[Object.keys(result)[0]]);
            }
          }
          return _results;
        })();
        if (processtools.constructorNameOf(data[0]) === 'Relationship') {
          return processtools.populateResultWithDocuments(data, options, cb);
        } else {
          return processtools.populateResultWithDocuments(data, options, cb);
        }
      } else {
        if (typeof cb === 'function') {
          return cb(errGraph, map || null, options);
        }
      }
    });
  };
  Document.prototype.findCorrespondingNode = function(options, cb) {
    var collectionName, doc, id, _processNode, _ref1, _ref2, _ref3, _ref4;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    doc = this;
    if ((_ref2 = options.forceReload) == null) {
      options.forceReload = false;
    }
    if (globalOptions.cacheAttachedNodes && doc._cached_node && options.forceReload !== true) {
      return cb(null, doc._cached_node, options);
    }
    collectionName = doc.constructor.collection.name;
    id = processtools.getObjectIDAsString(doc);
    if ((_ref3 = options.doCreateIfNotExists) == null) {
      options.doCreateIfNotExists = false;
    }
    if ((_ref4 = options.forceCreation) == null) {
      options.forceCreation = false;
    }
    _processNode = function(node, doc, cb) {
      if (globalOptions.storeDocumentInGraphDatabase) {
        node.data = doc.toObject(globalOptions.storeDocumentInGraphDatabase);
        node.save();
      }
      doc._node_id = node.id;
      if (globalOptions.cacheAttachedNodes) {
        doc._cached_node = node;
      }
      return cb(null, node, options);
    };
    if (doc.isNew === true && options.forceCreation !== true) {
      return cb(new Error("Can't return a 'corresponding' node of an unpersisted document"), null, options);
    } else if (doc._node_id) {
      return graphdb.getNodeById(doc._node_id, function(errFound, node) {
        if (errFound) {
          return cb(errFound, node, options);
        } else {
          return _processNode(node, doc, cb);
        }
      });
    } else if (options.doCreateIfNotExists || options.forceCreation === true) {
      node = graphdb.createNode({
        _id: id,
        collection: collectionName
      });
      return node.save(function(errSave, node) {
        if (errSave) {
          return cb(errSave, node, options);
        } else {
          node.index(collectionName, '_id', id);
          return _processNode(node, doc, cb);
        }
      });
    } else {
      return cb(null, null, options);
    }
  };
  Document.prototype.findOrCreateCorrespondingNode = function(options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    return this.findCorrespondingNode(options, cb);
  };
  Document.prototype.getNode = Document.prototype.findOrCreateCorrespondingNode;
  Document.prototype.getNodeId = function(cb) {
    if (this._node_id) {
      return cb(null, this._node_id);
    } else {
      return this.getNode(cb);
    }
  };
  Document.prototype.createRelationshipTo = function(doc, typeOfRelationship, attributes, cb) {
    var _ref1, _ref2, _ref3;

    if (attributes == null) {
      attributes = {};
    }
    if (typeof attributes === 'function') {
      cb = attributes;
      attributes = {};
    }
    if (globalOptions.relationships.storeIDsInRelationship) {
      if ((_ref1 = attributes._to) == null) {
        attributes._to = doc.constructor.collection.name + ":" + String(doc._id);
      }
      if ((_ref2 = attributes._from) == null) {
        attributes._from = this.constructor.collection.name + ":" + String(this._id);
      }
    }
    if (globalOptions.relationships.storeTimestamp) {
      if ((_ref3 = attributes._created_at) == null) {
        attributes._created_at = Math.floor(Date.now() / 1000);
      }
    }
    return this.findOrCreateCorrespondingNode(function(fromErr, from) {
      return doc.findOrCreateCorrespondingNode(function(toErr, to) {
        if (from && to) {
          return from.createRelationshipTo(to, typeOfRelationship, attributes, cb);
        } else {
          if (typeof cb === 'function') {
            return cb(fromErr || toErr, null);
          }
        }
      });
    });
  };
  Document.prototype.createRelationshipFrom = function(doc, typeOfRelationship, attributes, cb) {
    if (attributes == null) {
      attributes = {};
    }
    return doc.createRelationshipTo(this, typeOfRelationship, attributes, cb);
  };
  Document.prototype.createRelationshipBetween = function(doc, typeOfRelationship, attributes, cb) {
    var found, self;

    if (attributes == null) {
      attributes = {};
    }
    self = this;
    found = [];
    return self.createRelationshipTo(doc, typeOfRelationship, attributes, function(err, first) {
      if (err) {
        return cb(err);
      }
      found.push(first);
      return doc.createRelationshipTo(self, typeOfRelationship, attributes, function(err, second) {
        if (err) {
          return cb(err);
        }
        found.push(second);
        if (typeof cb === 'function') {
          return cb(err, found);
        }
      });
    });
  };
  Document.prototype.queryGraph = function(chypherQuery, options, cb) {
    var doc, _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    doc = this;
    return _queryGraphDB(chypherQuery, options, cb);
  };
  Document.prototype.queryRelationships = function(typeOfRelationship, options, cb) {
    var doc, id, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6;

    if (typeof options === 'string') {
      options = {
        query: options
      };
    }
    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    if (typeOfRelationship == null) {
      typeOfRelationship = '*';
    }
    typeOfRelationship = /^[*:]{1}$/.test(typeOfRelationship) || !typeOfRelationship ? '' : ':' + typeOfRelationship;
    if ((_ref2 = options.direction) == null) {
      options.direction = 'both';
    }
    if ((_ref3 = options.action) == null) {
      options.action = "RETURN";
    }
    if ((_ref4 = options.processPart) == null) {
      options.processPart = "relation";
    }
    if ((_ref5 = options.referenceDocumentID) == null) {
      options.referenceDocumentID = this._id;
    }
    if ((_ref6 = options.endNode) == null) {
      options.endNode = "";
    }
    if (typeof endNode === 'object') {
      options.endNode = endNode.id;
    }
    doc = this;
    id = processtools.getObjectIDAsString(doc);
    return this.getNode(function(nodeErr, fromNode) {
      var cypher, _ref7;

      if (nodeErr) {
        return cb(nodeErr, null);
      }
      cypher = "START a = node(%(id)s)%(endNode)s\nMATCH (a)%(incoming)s[relation%(relation)s]%(outgoing)s(b)\n%(action)s %(processPart)s;";
      cypher = _s.sprintf(cypher, {
        id: fromNode.id,
        incoming: options.direction === 'incoming' ? '<-' : '-',
        outgoing: options.direction === 'outgoing' ? '->' : '-',
        relation: typeOfRelationship,
        action: options.action.toUpperCase(),
        processPart: options.processPart,
        endNode: options.endNode ? ", b = node(" + options.endNode + ")" : ''
      });
      if ((_ref7 = options.startNode) == null) {
        options.startNode = fromNode.id;
      }
      if (options.query) {
        cypher = query;
      }
      if (options.dontExecute) {
        return cb({
          message: "`dontExecute` options is set",
          query: cypher,
          options: options
        }, null);
      } else {
        return _queryGraphDB(cypher, options, cb);
      }
    });
  };
  Document.prototype.allRelationships = function(typeOfRelationship, options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    options.direction = 'both';
    options.referenceDocumentID = this._id;
    return this.queryRelationships(typeOfRelationship, options, cb);
  };
  Document.prototype.incomingRelationships = function(typeOfRelationship, options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    options.direction = 'incoming';
    options.referenceDocumentID = this._id;
    return this.queryRelationships(typeOfRelationship, options, cb);
  };
  Document.prototype.outgoingRelationships = function(typeOfRelationship, options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    options.direction = 'outgoing';
    options.referenceDocumentID = this._id;
    return this.queryRelationships(typeOfRelationship, options, cb);
  };
  Document.prototype.removeRelationshipsTo = function(doc, typeOfRelationship, options, cb) {
    var from, _ref1, _ref2;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    if ((_ref2 = options.direction) == null) {
      options.direction = 'outgoing';
    }
    options.action = 'DELETE';
    from = this;
    return doc.getNode(function(nodeErr, endNode) {
      if (nodeErr) {
        return cb(nodeErr, endNode);
      }
      options.endNode = endNode.id;
      return from.queryRelationships(typeOfRelationship, options, cb);
    });
  };
  Document.prototype.removeRelationshipsFrom = function(doc, typeOfRelationship, options, cb) {
    var to;

    to = this;
    return doc.removeRelationshipsTo(to, typeOfRelationship, options, cb);
  };
  Document.prototype.removeRelationshipsBetween = function(doc, typeOfRelationship, options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    options.direction = 'both';
    return this.removeRelationshipsTo(doc, typeOfRelationship, options, cb);
  };
  Document.prototype.removeRelationships = function(typeOfRelationship, options, cb) {
    var _ref1;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    options.direction = 'both';
    options.action = 'DELETE';
    return this.queryRelationships(typeOfRelationship, options, cb);
  };
  Document.prototype.removeNode = function(options, cb) {
    var doc, _ref1, _ref2;

    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    if ((_ref2 = options.includeRelationships) == null) {
      options.includeRelationships = true;
    }
    doc = this;
    return doc.getNode(function(err, node) {
      var cypher;

      if (err || typeof node !== 'object') {
        if (typeof cb === 'function') {
          return cb(err || new Error('No corresponding node found to document #' + doc._id), node);
        }
      } else {
        cypher = "START n = node(" + node.id + ")\nMATCH n-[r?]-()\nDELETE n" + (options.includeRelationships ? ', r' : '');
        return _queryGraphDB(cypher, options, cb);
      }
    });
  };
  Document.prototype.shortestPathTo = function(doc, typeOfRelationship, options, cb) {
    var from, to, _ref1;

    if (typeOfRelationship == null) {
      typeOfRelationship = '';
    }
    _ref1 = processtools.sortOptionsAndCallback(options, cb), options = _ref1.options, cb = _ref1.cb;
    from = this;
    to = doc;
    return from.getNode(function(errFrom, fromNode) {
      return to.getNode(function(errTo, toNode) {
        var levelDeepness, query;

        if (errFrom || errTo || !fromNode || !toNode) {
          return cb(new Error("Problem(s) getting from and/or to node"));
        }
        levelDeepness = 15;
        query = "START a = node(" + fromNode.id + "), b = node(" + toNode.id + ") \nMATCH p = shortestPath( a-[" + (typeOfRelationship ? ':' + typeOfRelationship : '') + "*.." + levelDeepness + "]->b )\nRETURN p;";
        return from.queryGraph(query, options, cb);
      });
    });
  };
  if (globalOptions.cacheAttachedNodes) {
    return Document.prototype._cached_node = null;
  }
};
