// Generated by CoffeeScript 1.6.2
var exports, mongraphMongoosePlugin, processtools;

processtools = require('./processtools');

module.exports = exports = mongraphMongoosePlugin = function(schema, options) {
  var schemaOptions, _base, _base1, _base2, _base3, _base4, _base5, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;

  if (options == null) {
    options = {};
  }
  schemaOptions = schema.options;
  if (schemaOptions.graphability === false) {
    return null;
  }
  if ((_ref = schemaOptions.graphability) == null) {
    schemaOptions.graphability = {};
  }
  if ((_ref1 = (_base = schemaOptions.graphability).schema) == null) {
    _base.schema = true;
  }
  if ((_ref2 = (_base1 = schemaOptions.graphability).middleware) == null) {
    _base1.middleware = true;
  }
  if (schemaOptions.graphability.middleware && typeof schemaOptions.graphability.middleware !== 'object') {
    schemaOptions.graphability.middleware = {};
  }
  if ((_ref3 = (_base2 = schemaOptions.graphability.middleware).preRemove) == null) {
    _base2.preRemove = true;
  }
  if ((_ref4 = (_base3 = schemaOptions.graphability.middleware).preSave) == null) {
    _base3.preSave = true;
  }
  if ((_ref5 = options.relationships) == null) {
    options.relationships = {};
  }
  if ((_ref6 = (_base4 = options.relationships).removeAllOutgoing) == null) {
    _base4.removeAllOutgoing = true;
  }
  if ((_ref7 = (_base5 = options.relationships).removeAllIncoming) == null) {
    _base5.removeAllIncoming = true;
  }
  if (schemaOptions.graphability.schema) {
    schema.add({
      _node_id: Number
    }, schema.add({
      _relationships: {}
    }));
  }
  if (schemaOptions.graphability.middleware.preRemove) {
    schema.pre('remove', function(errHandler, next) {
      var opts;

      if (!this._node_id) {
        return next(null);
      }
      opts = {
        includeRelationships: options.relationships.removeAllOutgoing && options.relationships.removeAllOutgoing
      };
      return this.removeNode(opts, next);
    });
  }
  if (schemaOptions.graphability.middleware.preSave) {
    return schema.pre('save', true, function(next, done) {
      var doc;

      doc = this;
      next();
      return doc.getNode({
        forceCreation: true
      }, done);
    });
  }
};
