// Generated by CoffeeScript 1.6.2
var exports, mongraphMongoosePlugin, processtools;

processtools = require('./processtools');

module.exports = exports = mongraphMongoosePlugin = function(schema, options) {
  var _base, _base1, _ref, _ref1, _ref2;

  if (options == null) {
    options = {};
  }
  if ((_ref = options.relationships) == null) {
    options.relationships = {};
  }
  if ((_ref1 = (_base = options.relationships).removeAllOutgoing) == null) {
    _base.removeAllOutgoing = true;
  }
  if ((_ref2 = (_base1 = options.relationships).removeAllIncoming) == null) {
    _base1.removeAllIncoming = true;
  }
  schema.add({
    _node_id: Number
  }, schema.add({
    _relationships: {}
  }));
  schema.pre('remove', function(errHandler, cb) {
    var opts;

    opts = {
      includeRelationships: options.relationships.removeAllOutgoing && options.relationships.removeAllOutgoing
    };
    return this.removeNode(opts, cb);
  });
  return schema.pre('save', true, function(next, done) {
    var doc;

    doc = this;
    next();
    return doc.getNode({
      forceCreation: true
    }, done);
  });
};
