// Generated by CoffeeScript 1.6.2
var Join, ObjectId, constructorNameOf, getModelByCollectionName, getObjectIDAsString, getObjectIDsAsArray, getObjectIdFromString, loadDocumentsFromNodeArray, loadDocumentsFromRelationshipArray, sortOptionsAndCallback, _extractCollectionAndId;

ObjectId = require('bson').ObjectID;

Join = require('join');

sortOptionsAndCallback = function(options, cb) {
  if (typeof options === 'function') {
    return {
      options: {},
      cb: options
    };
  } else {
    return {
      options: options || {},
      cb: cb
    };
  }
};

constructorNameOf = function(f) {
  var _ref, _ref1;

  return f != null ? (_ref = f.constructor) != null ? (_ref1 = _ref.toString().match(/function\s+(.+?)\(/)[1]) != null ? _ref1.trim() : void 0 : void 0 : void 0;
};

_extractCollectionAndId = function(s) {
  var parts;

  if ((parts = s.split(":"))) {
    return {
      collectionName: parts[0],
      _id: parts[1]
    };
  }
};

getObjectIDAsString = function(obj) {
  if (typeof obj === 'string') {
    return obj;
  } else if (typeof obj === 'object') {
    return String(obj._id || obj);
  } else {
    return '';
  }
};

getObjectIdFromString = function(s) {
  return new ObjectId(s);
};

getObjectIDsAsArray = function(mixed) {
  var id, ids, item, _i, _len;

  ids = [];
  if ((mixed != null ? mixed.constructor : void 0) === Array) {
    for (_i = 0, _len = mixed.length; _i < _len; _i++) {
      item = mixed[_i];
      if (id = getObjectIDAsString(item)) {
        ids.push(id);
      }
    }
  } else {
    ids = [getObjectIDAsString(mixed)];
  }
  return ids;
};

loadDocumentsFromNodeArray = function(result, cb) {
  var arrayWithNodes, callbackDocument, i, join, node, _i, _len, _ref;

  arrayWithNodes = (_ref = result[0]) != null ? _ref.nodes : void 0;
  if (!arrayWithNodes) {
    return cb("Couldn't find any nodes to process", result);
  }
  join = Join.create();
  for (i = _i = 0, _len = arrayWithNodes.length; _i < _len; i = ++_i) {
    node = arrayWithNodes[i];
    if (node.id) {
      callbackDocument = join.add();
      node.getDocument(callbackDocument);
    }
  }
  return join.when(function() {
    var data, err, item, _j, _len1;

    err = null;
    data = [];
    for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
      item = arguments[_j];
      err = item[0];
      data.push(item[1]);
    }
    return cb(err, data);
  });
};

loadDocumentsFromRelationshipArray = function(mongodb, graphResultset, cb) {
  var i, join, relation, relations, _fn, _i, _j, _len, _len1;

  if (constructorNameOf(mongodb) !== 'NativeConnection') {
    return cb('Need db connection as argument', null, graphResultset);
  }
  if (!((graphResultset != null ? graphResultset.constructor : void 0) === Array || (graphResultset = getObjectIDsAsArray(graphResultset)).constructor === Array)) {
    return cb('No Array given', null, graphResultset);
  }
  relations = [];
  for (i = _i = 0, _len = graphResultset.length; _i < _len; i = ++_i) {
    relation = graphResultset[i];
    if (constructorNameOf(relation) === 'Relationship') {
      relations.push(relation);
    }
  }
  if (!(relations.length > 0)) {
    return cb(null, null, graphResultset);
  }
  join = Join.create();
  _fn = function(i, relation) {
    var callbackFrom, callbackTo, collectionName, id, _id, _ref, _ref1;

    _ref = _extractCollectionAndId(relation.data._to), collectionName = _ref.collectionName, _id = _ref._id;
    id = getObjectIdFromString(_id);
    callbackTo = join.add();
    mongodb.collection(collectionName).findOne({
      _id: id
    }, function(err, doc) {
      relation.to = doc;
      return callbackTo(err, relation);
    });
    _ref1 = _extractCollectionAndId(relation.data._from), collectionName = _ref1.collectionName, _id = _ref1._id;
    id = getObjectIdFromString(_id);
    callbackFrom = join.add();
    return mongodb.collection(collectionName).findOne({
      _id: id
    }, function(err, doc) {
      relation.from = doc;
      return callbackFrom(err, relation);
    });
  };
  for (i = _j = 0, _len1 = relations.length; _j < _len1; i = ++_j) {
    relation = relations[i];
    _fn(i, relation);
  }
  return join.when(function() {
    return cb(null, relations, graphResultset);
  });
};

getModelByCollectionName = function(collectionName, mongoose) {
  var i, models, name, nameOfModel;

  if (constructorNameOf(mongoose) === 'Mongoose') {
    models = mongoose.models;
  } else if (!mongoose) {
    return null;
  } else {
    models = mongoose;
  }
  name = null;
  for (nameOfModel in models) {
    i = models[nameOfModel];
    if (collectionName === models[nameOfModel].collection.name) {
      name = models[nameOfModel].modelName;
    }
  }
  return name;
};

module.exports = {
  getObjectIDAsString: getObjectIDAsString,
  getObjectIDsAsArray: getObjectIDsAsArray,
  loadDocumentsFromRelationshipArray: loadDocumentsFromRelationshipArray,
  loadDocumentsFromNodeArray: loadDocumentsFromNodeArray,
  constructorNameOf: constructorNameOf,
  getObjectIdFromString: getObjectIdFromString,
  sortOptionsAndCallback: sortOptionsAndCallback,
  getModelByCollectionName: getModelByCollectionName
};
